runtime: python311

# Cloud Run configuration
env_variables:
  FLET_WEB_RENDERER: html
  PORT: 8080

# Instance configuration
instance_class: F2
scaling:
  min_instances: 0
  max_instances: 10
  
# Health check
readiness_check:
  path: "/"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

liveness_check:
  path: "/"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 4
  success_threshold: 2
